const ROLES = {
  ADMIN: 'admin',
  COUNSELOR: 'counselor'
};

const ENQUIRY_STATUSES = {
  NEW: 'NEW',
  CONTACTED: 'CONTACTED',
  NO_RESPONSE: 'NO_RESPONSE',
  FOLLOW_UP: 'FOLLOW_UP',
  INTERESTED: 'INTERESTED',
  NOT_INTERESTED: 'NOT_INTERESTED',
  ADMISSION_PROCESS: 'ADMISSION_PROCESS',
  CONVERTED: 'CONVERTED'
};

const STATUS_LIST = Object.values(ENQUIRY_STATUSES);

const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100
};

const JWT_CONFIG = {
  EXPIRE: process.env.JWT_EXPIRE || '7d',
  SECRET: process.env.JWT_SECRET
};

const BCRYPT_CONFIG = {
  SALT_ROUNDS: parseInt(process.env.BCRYPT_SALT_ROUNDS) || 12
};

const PAYMENT_TYPES = {
  ONE_TIME: 'ONE_TIME',
  INSTALLMENT: 'INSTALLMENT'
};

const TIMELINE_TYPES = {
  CREATED: 'created',
  STATUS_CHANGE: 'status_change',
  NOTE: 'note',
  FOLLOWUP: 'followup',
  CONVERTED: 'converted',
  PAYMENT: 'payment',
  PAYMENT_UPDATED: 'payment_updated',
  LOCKED: 'locked',
  FEES_UPDATED: 'fees_updated',
  PAYMENT_PLAN_SET: 'payment_plan_set',
  INSTALLMENT_CREATED: 'installment_created',
  INSTALLMENT_PAID: 'installment_paid',
  FULL_PAYMENT_COMPLETED: 'full_payment_completed'
};

// Status flow control - defines valid transitions from each status
// FOLLOW_UP is allowed from any status before conversion for multiple follow-up scenarios
const STATUS_FLOW = {
  [ENQUIRY_STATUSES.NEW]: [ENQUIRY_STATUSES.CONTACTED, ENQUIRY_STATUSES.NO_RESPONSE, ENQUIRY_STATUSES.FOLLOW_UP],
  [ENQUIRY_STATUSES.CONTACTED]: [ENQUIRY_STATUSES.FOLLOW_UP, ENQUIRY_STATUSES.INTERESTED, ENQUIRY_STATUSES.NOT_INTERESTED],
  [ENQUIRY_STATUSES.NO_RESPONSE]: [ENQUIRY_STATUSES.CONTACTED, ENQUIRY_STATUSES.FOLLOW_UP, ENQUIRY_STATUSES.INTERESTED, ENQUIRY_STATUSES.NOT_INTERESTED],
  [ENQUIRY_STATUSES.FOLLOW_UP]: [ENQUIRY_STATUSES.CONTACTED, ENQUIRY_STATUSES.INTERESTED, ENQUIRY_STATUSES.NOT_INTERESTED],
  [ENQUIRY_STATUSES.INTERESTED]: [ENQUIRY_STATUSES.FOLLOW_UP, ENQUIRY_STATUSES.ADMISSION_PROCESS, ENQUIRY_STATUSES.NOT_INTERESTED],
  [ENQUIRY_STATUSES.ADMISSION_PROCESS]: [ENQUIRY_STATUSES.FOLLOW_UP, ENQUIRY_STATUSES.CONVERTED, ENQUIRY_STATUSES.NOT_INTERESTED],
  [ENQUIRY_STATUSES.NOT_INTERESTED]: [], // Terminal state
  [ENQUIRY_STATUSES.CONVERTED]: [] // Terminal state - only admin can modify
};

module.exports = {
  ROLES,
  ENQUIRY_STATUSES,
  STATUS_LIST,
  STATUS_FLOW,
  PAGINATION,
  JWT_CONFIG,
  BCRYPT_CONFIG,
  PAYMENT_TYPES,
  TIMELINE_TYPES
};
